# Generated by Django 4.1.4 on 2024-01-26 09:45

from django.db import migrations, models

import django_country_kit.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "country",
                    django_country_kit.fields.CountryField(
                        choices=[("AF", "Afghanistan"), ("AL", "Albania")], max_length=2
                    ),
                ),
            ],
        ),
    ]
